/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

 * @param {string} s
 * @param {string} t
 * @return {character}
 */
const findTheDifference = function(s, t) {
  let sArray = s.split('');
  let tArray = t.split('');
  for (let i = 0; i < tArray.length; i++) {
    for (let k = 0; k < sArray.length; k++) {
      if (tArray[i] === sArray[k]) {
        tArray.splice(i, 1);
      }  
    }
  };
  
  return tArray.toString();
  
};

//inc, does not work with long strings